services:
  backend:
    command: >
      python -m debugpy
      --listen 0.0.0.0:5678
      --wait-for-client
      -m django runserver 0.0.0.0:30000 --noreload
    ports:
      - "30000:30000"
      - "5678:5678"
